// LIBRARIES
// https://getuikit.com/docs/introduction
// https://mithril.js.org/
// ICONS
// https://thenounproject.com/smashicons/collection/smashicons-man-footwear-outline/
// https://thenounproject.com/smashicons/collection/smashicons-man-accessories-outline/
// https://thenounproject.com/smashicons/collection/smashicons-men-clothes-outline/
// https://thenounproject.com/smashicons/collection/smashicons-the-essentials-outline/
// https://thenounproject.com/smashicons/collection/smashicons-woman-accessories-outline/
// https://thenounproject.com/smashicons/collection/smashicons-weather-outline/
// https://thenounproject.com/smashicons/collection/smashicons-households-2-outline/
// https://thenounproject.com/ratch0013/collection/jewelry/
// https://thenounproject.com/luke.locad/collection/mens-clothing-outline/
var Data = {
	// Architecture
	jsonLoc: '../json/',
	jsonFile: 'wardrobe.json',
	cookieName: 'wardrobe_login',
	localStorageName: 'wardrobe_json',
	imgLoc: './img/svg/',
	imgFile: '.svg',
	waitTime: 100,
	
	// Errors and messages
	messages: {
		loginIncomplete: 'Both username and password are required!',
		loginIncorrect: 'Login or password incorrect!',
		noPromises: 'This browser doesn\'t support Promises',
		loginCorrect: 'Logged in successfully!',
		jsonWriteFail: 'Failed to write new wardrobe.json',
		needNewJSON: 'No wardrobe file present, creating one...',
		alreadyLoggedIn: 'You are already logged in',
		loggedOut: 'Logged out!',
		noItems: 'No items in this group',
	},
	
	// Time
	minute: 1 * 60 * 1000,		// 1 minute
	day: 24 * 60 * 60 * 1000, 	// 1 day
	week: 7 * 24 * 60 * 60 * 1000,	// 1 week
	
	// Item Groups and Types
	labels: {
		username: 'username',
		password: 'password',
		login: 'login',
		help: 'help',
		top: 'top',
		bottom: 'bottom',
		over: 'over',
		under: 'under',
		around: 'accessory',
		shoe: 'shoe',
		hat: 'hat',
		outfit: 'outfit',
		group: 'group',
		type: 'type',
		name: 'name',
		brand: 'brand',
		color1: 'primary color',
		color2: 'secondary color (optional)',
		color3: 'accent color (optional)',
		pattern: 'pattern',
		price: 'price',
		purchased: 'purchased',
		formality: 'formality',
		material: 'material',
		size: 'size',
		warmth: 'warmth',
		fit: 'fit',
		wear: 'wear',
		sleeveLength: 'sleeve length',
		width: 'width',
		height: 'height',
		notes: 'notes',
		addItem: 'add item',
		addOutfit: 'add outfit',
		optional: 'optional',
		required: 'required',
	},
	itemIDSeparator: '_',
	defaults: {
		formality: 'casual',
		pattern: 'none',
		sleeveLength: 'short',
		wear: 'like-new',
		fit: 'fits well',
		warmth: 'warm',	
	},
	groups: [ 'top', 'bottom', 'over', 'under', 'around', 'shoe', 'hat' ],
	types: {
		top: [ 'tshirt', 'tanktop', 'polo', 'buttonup' ],
		bottom: [ 'jeans', 'jogger', 'shorts', 'trunks', 'pajama', 'khaki', 'slacks' ],
		over: [ 'snow', 'lightweight', 'rain', 'hoodie', 'sweatshirt', 'vest', 'suitjacket', 'blazer', 'sweater', 'cardigan' ],
		under: [ 'undershirt', 'wifebeater', 'underwear', 'sock' ],
		around: [ 'ring', 'necklace', 'bracelet', 'belt', 'tie', 'gloves', 'watch', 'scarf', 'earring', 'sunglasses' ],
		shoe: [ 'sport', 'boot', 'sandal', 'fashion', 'formal' ],
		hat: [ 'baseball', 'brimmed', 'beanie' ],
	},
	sleeveLengths: [ 'none', 'short', 'middle', 'long' ],
	materials: [ 'cotton', 'wool', 'denim', 'canvas', 'linen', 'leather', 'suede/nubuck', 'polyester', 'silk', 'nylon', 'velvet', 'satin', 'blend', 'unknown', 'metal', 'fur', 'blend', 'plastic', 'rubber' ],	
	sizes: [ 'xs', 's', 'm', 'l', 'xl', '2xl', '3xl', '4xl' ],
	warmthLevels: [ 'cold', 'warm', 'hot' ],
	formalityLevels: [ 'sport', 'casual', 'business casual', 'business formal', 'semi-formal', 'formal', 'black tie', 'white tie' ],
	fitLevels: [ 'too small', 'small', 'fits well', 'big', 'too big' ],
	wearLevels: [ 'destroyed', 'ratty', 'worn', 'like-new', 'pristine', 'never worn' ],
	patterns: [ 'heather', 'houndstooth', 'plaid', 'stripe', 'dots', 'graphic', 'none', 'paisley', 'geometric', 'basketweave', 'checked', 'floral', 'chevron', 'gingham', 'harlequin', 'herringbone', 'animal print', 'toile' ],
	typeChecks: {
		metal: [ 'ring', 'necklace', 'bracelet' ],
		cotton: [ 'tshirt', 'wifebeater', 'tank top', 'hoodie', 'sweatshirt', 'underwear', 'socks' ],
		silk: [ 'tie' ],
		denim: [ 'jeans' ],
		leather: [ 'belt', 'formal' ],
		noSleeve: [ 'tanktop', 'wifebeater' ],
		noLength: [ 'shorts', 'trunks' ],
	},
	
	colors: {
		'aliceblue': '#f0f8ff',
		'antiquewhite': '#faebd7',
		'aqua': '#00ffff',
		'aquamarine': '#7fffd4',
		'azure': '#f0ffff',
		'beige': '#f5f5dc',
		'bisque': '#ffe4c4',
		'black': '#000000',
		'blanchedalmond': '#ffebcd',
		'blue': '#0000ff',
		'blueviolet': '#8a2be2',
		'brown': '#a52a2a',
		'burlywood': '#deb887',
		'cadetblue': '#5f9ea0',
		'chartreuse': '#7fff00',
		'chocolate': '#d2691e',
		'coral': '#ff7f50',
		'cornflowerblue': '#6495ed',
		'cornsilk': '#fff8dc',
		'crimson': '#dc143c',
		'cyan': '#00ffff',
		'darkblue': '#00008b',
		'darkcyan': '#008b8b',
		'darkgoldenrod': '#b8860b',
		'darkgray': '#a9a9a9',
		'darkgreen': '#006400',
		'darkkhaki': '#bdb76b',
		'darkmagenta': '#8b008b',
		'darkolivegreen': '#556b2f',
		'darkorange': '#ff8c00',
		'darkorchid': '#9932cc',
		'darkred': '#8b0000',
		'darksalmon': '#e9967a',
		'darkseagreen': '#8fbc8f',
		'darkslateblue': '#483d8b',
		'darkslategray': '#2f4f4f',
		'darkturquoise': '#00ced1',
		'darkviolet': '#9400d3',
		'deeppink': '#ff1493',
		'deepskyblue': '#00bfff',
		'dimgray': '#696969',
		'dodgerblue': '#1e90ff',
		'firebrick': '#b22222',
		'floralwhite': '#fffaf0',
		'forestgreen': '#228b22',
		'fuchsia': '#ff00ff',
		'gainsboro': '#dcdcdc',
		'ghostwhite': '#f8f8ff',
		'gold': '#ffd700',
		'goldenrod': '#daa520',
		'gray': '#808080',
		'green': '#008000',
		'greenyellow': '#adff2f',
		'grey': '#808080',
		'honeydew': '#f0fff0',
		'hotpink': '#ff69b4',
		'indianred': '#cd5c5c',
		'indigo': '#4b0082',
		'ivory': '#fffff0',
		'khaki': '#f0e68c',
		'lavender': '#e6e6fa',
		'lavenderblush': '#fff0f5',
		'lawngreen': '#7cfc00',
		'lemonchiffon': '#fffacd',
		'lightblue': '#add8e6',
		'lightcoral': '#f08080',
		'lightcyan': '#e0ffff',
		'lightgoldenrodyellow': '#fafad2',
		'lightgray': '#d3d3d3',
		'lightgreen': '#90ee90',
		'lightpink': '#ffb6c1',
		'lightsalmon': '#ffa07a',
		'lightseagreen': '#20b2aa',
		'lightskyblue': '#87cefa',
		'lightslategray': '#778899',
		'lightsteelblue': '#b0c4de',
		'lightyellow': '#ffffe0',
		'lime': '#00ff00',
		'limegreen': '#32cd32',
		'linen': '#faf0e6',
		'magenta': '#ff00ff',
		'maroon': '#800000',
		'mediumaquamarine': '#66cdaa',
		'mediumblue': '#0000cd',
		'mediumorchid': '#ba55d3',
		'mediumpurple': '#9370db',
		'mediumseagreen': '#3cb371',
		'mediumslateblue': '#7b68ee',
		'mediumspringgreen': '#00fa9a',
		'mediumturquoise': '#48d1cc',
		'mediumvioletred': '#c71585',
		'midnightblue': '#191970',
		'mintcream': '#f5fffa',
		'mistyrose': '#ffe4e1',
		'moccasin': '#ffe4b5',
		'navajowhite': '#ffdead',
		'navy': '#000080',
		'oldlace': '#fdf5e6',
		'olive': '#808000',
		'olivedrab': '#6b8e23',
		'orange': '#ffa500',
		'orangered': '#ff4500',
		'orchid': '#da70d6',
		'palegoldenrod': '#eee8aa',
		'palegreen': '#98fb98',
		'paleturquoise': '#afeeee',
		'palevioletred': '#db7093',
		'papayawhip': '#ffefd5',
		'peachpuff': '#ffdab9',
		'peru': '#cd853f',
		'pink': '#ffc0cb',
		'plum': '#dda0dd',
		'powderblue': '#b0e0e6',
		'purple': '#800080',
		'rebeccapurple': '#663399',
		'red': '#ff0000',
		'rosybrown': '#bc8f8f',
		'royalblue': '#4169e1',
		'saddlebrown': '#8b4513',
		'salmon': '#fa8072',
		'sandybrown': '#f4a460',
		'seagreen': '#2e8b57',
		'seashell': '#fff5ee',
		'sienna': '#a0522d',
		'silver': '#c0c0c0',
		'skyblue': '#87ceeb',
		'slateblue': '#6a5acd',
		'slategray': '#708090',
		'snow': '#fffafa',
		'springgreen': '#00ff7f',
		'steelblue': '#4682b4',
		'tan': '#d2b48c',
		'teal': '#008080',
		'thistle': '#d8bfd8',
		'tomato': '#ff6347',
		'turquoise': '#40e0d0',
		'violet': '#ee82ee',
		'wheat': '#f5deb3',
		'white': '#ffffff',
		'whitesmoke': '#f5f5f5',
		'yellow': '#ffff00',
		'yellowgreen': '#9acd32'
	},
	
	// DOM
	defaultColor: '#000000',
	defaultInputType: 'text',
	defaultButtonType: 'button',
	defaultLabelText: 'Input',
	defaultButtonText: 'Go',
	inputTypes: [
		'text', 'date', 'email', 'number', 'range', 'color', 'checkbox', 'radio', 
		'search', 'tel', 'password', 'hidden', 'time',
	],
	buttonTypes: [
		'button', 'submit', 'reset'
	],
	randomStringLength: 8,
	inputID: 'input_',
	containerID: 'container_',
	labelID: 'label_',
	buttonID: 'button_',
	colorID: 'color_',
	tabID: 'tab_',
	cardID: 'card_',
	notifications: {
		position: 'bottom-right',
		timeout: 2000,
	},
	defaultTextareaRows: 3,
	icons: {
		// Generic
		generic: 'noun_generic',
		cold: 'noun_cold',
		warm: 'noun_warm',
		hot: 'noun_hot',
		// Top
		tshirt: 'noun_tshirt',
		tanktop: 'noun_tanktop',
		buttonup: 'noun_buttonup',
		polo: 'noun_polo',
		// Bottom
		shorts: 'noun_shorts',
		trunks: 'noun_trunks',
		jeans: 'noun_pants',
		khaki: 'noun_khakis',
		slacks: 'noun_slacks',
		jogger: 'noun_jogger',
		pajama: 'noun_jogger',
		// Over
		sweater: 'noun_sweater',
		cardigan: 'noun_cardigan',
		hoodie: 'noun_hoodie',
		snow: 'noun_snow',
		lightweight: 'noun_lightweight',
		rain: 'noun_rain',
		sweatshirt: 'noun_sweatshirt',
		vest: 'noun_vest',
		suitjacket: 'noun_jacket',
		blazer: 'noun_jacket',
		// Under
		sock: 'noun_sock',
		wifebeater: 'noun_wifebeater',
		undershirt: 'noun_undershirt',
		underwear: 'noun_underwear',
		// Around
		belt: 'noun_belt',
		bowtie: 'noun_bowtie',
		gloves: 'noun_gloves',
		necklace: 'noun_necklace',
		scarf: 'noun_scarf',
		sunglasses: 'noun_sunglasses',
		tie: 'noun_tie',
		watch: 'noun_watch',
		ring: 'noun_ring',
		bracelet: 'noun_bracelet',
		earring: 'noun_earring',
		// Shoe
		fashion: 'noun_fashion',
		boot: 'noun_boot',
		formal: 'noun_formal',
		sport: 'noun_sport',
		sandal: 'noun_sandal',
		// Hat
		beanie: 'noun_beanie',
		brimmed: 'noun_brimmed',
		baseball: 'noun_baseball',
	},
	
	// Database
	user: false,
	json: false,
	db: {
		groups: {},		// Item groups pulled out from the JSON blob
	}
}